USE DB_PERSON;
GO

-- Tabela de pessoas
CREATE TABLE TB_PERSONS (
    PersonId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    RG VARCHAR(20) NOT NULL,
    IssuingAuthority VARCHAR(50) NOT NULL,
    RGIssuingState VARCHAR(2) NOT NULL,
    MaritalStatus VARCHAR(50) NOT NULL CHECK (MaritalStatus IN ('Single', 'Married', 'Divorced', 'Widowed', 'Legally Separated', 'Stable Union')),
    Profession VARCHAR(100),
    Nationality VARCHAR(50) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    CreatedBy VARCHAR(100) NOT NULL
);
GO

CREATE TABLE TB_EMAIL_PERSON (
    EmailIdPerson UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PersonId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_PERSONS(PersonId),  
    EmailAddress VARCHAR(255) NOT NULL,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NULL,
    IsActive BIT DEFAULT 1
);
GO

CREATE TABLE TB_PHONES_PERSON (
    PhoneIdPerson UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PersonId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_PERSONS(PersonId),  
    Type VARCHAR(20) NOT NULL CHECK (Type IN ('mobile', 'home', 'work')),
    Number VARCHAR(20) NOT NULL,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NULL,
    IsActive BIT DEFAULT 1
);
GO

CREATE TABLE TB_ADDRESSES_PERSON (
    AddressIdPerson UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PersonId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_PERSONS(PersonId), 
    Street VARCHAR(100) NOT NULL,
    Number VARCHAR(20) NOT NULL,
    AdditionalData VARCHAR(255),
    Neighborhood VARCHAR(100) NOT NULL,
    City VARCHAR(100) NOT NULL,
    State VARCHAR(2) NOT NULL,
    Country VARCHAR(50) NOT NULL,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NULL,
    IsActive BIT DEFAULT 1
);
GO
